### ISSUE TITLE
Mod not switching to silk touch

### ISSUE THREAD

**Issue by dapal-003** [thebombzen/AutoSwitch#12]
Heyo, every since today. I've no clue why, the mod kinda stopped working for me. The tools don't switch to silk touch for me. whilst mining stone it'd use a non silk touch over a silk touch one. Here is my log https://pastebin.com/KHjLwtDU

**Comment by Traneptora** [comment]
It's intentional to not use a silk touch pickaxe on smooth stone. AutoSwitch should correctly calculate that silk touch works on smooth stone, but the default configuration file has that behavior overridden since in nearly every use case you don't want to waste a silk touch pickaxe on smooth stone. This is not a surprise.

If you want to disable this behavior, find the line in the config file that says `T < stone` and comment it out (that is, place a `#` sign at the front).

**Comment by dapal-003** [comment]
Ah, alright. Thanks for that it's working correctly now. Uhh, I'd close this report if I'd know how.
